name: Check Go Project

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check Go Project
        run: |
          cd ./cmd
          go mod tidy && go build