name: Docker Image CI

on: [push]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          echo "${{ secrets.CONFIG_YAML }}" >> config.yaml
          docker login --username=${{ secrets.ALIYUN_REGISTRY_USER }} ${{ secrets.ALIYUN_REGISTRY }} -p ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
          docker buildx create --use
          docker buildx build .   --push --tag island:backend
